### ISSUE TITLE
Adapt platy-browser to new folder structure

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-platyBrowser#31]
I have refactored the layout of the platy browser data.
Before [merging this into master](https://git.embl.de/tischer/platy-browser-tables/merge_requests/2), the platy browser gui needs to be adapted.

List of necessary changes (what I could think of now, there might be more):
- [x] Parse [file prefixes](https://git.embl.de/tischer/platy-browser-tables/tree/dev#file-naming) for different modalities and translate them to nested drop-down menu for file selection.
- [x] Load tables from new format, see [table storage](https://git.embl.de/tischer/platy-browser-tables/tree/dev#table-storage). Also relates to #28.
- [x] Load bookmarks from `bookmarks.json`, see [example](https://git.embl.de/tischer/platy-browser-tables/blob/dev/data/0.0.0/misc/bookmarks.json). Also relates to #30.

**Comment by constantinpape** [comment]
@tischi you can find the new root folder here:
`/g/kreshuk/data/arendt/platyneris_v1/platy-browser-tables`.
The subfolder `data` contains the folders for individual versions.
Let me know if you have any permission issues.

**Comment by tischi** [comment]
I am trying but am getting below error for: 

`version 0.2.1, file sbem-6dpf-1-whole-raw.xml`

Can you open this?

```

Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5LowLevelIOException: Low-level I/O:Read failed ["H5FDsec2.c line 707 in H5FD_sec2_read(): file read failed: time = Thu Jul 11 13:17:55 2019"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Fis_hdf5(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5F.H5Fis_hdf5(H5F.java:127)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.isHDF5File(HDF5FactoryProvider.java:60)
	at ch.systemsx.cisd.hdf5.HDF5Factory.isHDF5File(HDF5Factory.java:113)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.openFile(HDF5BaseReader.java:204)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:147)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:126)
	at ch.systemsx.cisd.hdf5.HDF5ReaderConfigurator.reader(HDF5ReaderConfigurator.java:86)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.openForReading(HDF5FactoryProvider.java:54)
	at ch.systemsx.cisd.hdf5.HDF5Factory.openForReading(HDF5Factory.java:55)
```

**Comment by tischi** [comment]
Maybe I do not have read access?

**Comment by tischi** [comment]
```-rw-r--r-- 1 pape kreshuk  1086 Jul 11 09:53 sbem-6dpf-1-whole-raw.xml```
Can you give me also execute rights?

**Comment by constantinpape** [comment]
can you try again?

**Comment by constantinpape** [comment]
I think I might now the issue:
`sbem-6dpf-1-whole-raw.xml` points to the file `rawdata/sbem-6dpf-whole-raw.h5`, which
is a soft-link to `/g/arendt/.../em-raw-full-res.h5` (I didn't want to copy the whole 2 TB File).

If you are working on Mac (for example), this link location would not be valid though.
If you want, you can change the link for now.

**Comment by tischi** [comment]
How to change it?

```
login 25% ln -fn /Volumes/arendt/EM_6dpf_segmentation/EM-Prospr/em-segmented-tissue-labels.h5 sbem-6dpf-1-whole-segmented-tissue-labels.h5
ln: failed to access '/Volumes/arendt/EM_6dpf_segmentation/EM-Prospr/em-segmented-tissue-labels.h5': No such file or directory
```

Tried to call you...

**Comment by tischi** [comment]
Ok. Funktioniert alles denke ich.
Wegen mir können wir die Umstellung bald probieren.

**Comment by constantinpape** [comment]
Wir koennen ja schauen ob wir morgen noch Zeit fuer haben, ansonsten naechste Woche.

**Comment by constantinpape** [comment]
This is done.
