### ISSUE TITLE
3d view for arbitrary object sizes

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-platyBrowser#32]
It would be nice to have the 3d viewer work for arbitrary objects. (Right now it fails if the bounding box is larger than some threshold).

@tischi  Maybe you could just use downscaled versions of the segmentation if the bounding box is to large? In python / pseudocode:

```python
# given bounding_box, segmentation in h5 bdv format and object_id
scale = 0
mesh = None
# max_scale can be read from the h5 file
while scale <= max_scale:
  size_in_pixel = get_size_of_bounding_box(bounding_box, scale)
  if size_in_pixel < size_threshold:
    mesh = make_mesh(segmentation, scale, bounding_box, object_id)
    break
  scale += 1

if mesh is None:
  raise RuntimeError("Could not make mesh")
```

**Comment by tischi** [comment]
What about, as an option, I automatically choose the level such that the number of voxels that need to be loaded and rendered is reasonable? That means smaller objects could be rendered at higher resolution and larger objects will be rendered more coarse.

**Comment by constantinpape** [comment]
> What about, as an option, I automatically choose the level such that the number of voxels that need to be loaded and rendered is reasonable?

Yes, exactly.

That's also what the pseudo-code does ;).

**Comment by tischi** [comment]
I did it. One can now even see the neuropil!

<img width="732" alt="image" src="https://user-images.githubusercontent.com/2157566/61040173-66849200-a3d0-11e9-9f79-e42656f0db27.png">

But I could not find the chromatin files in the folder....?

**Comment by constantinpape** [comment]
Very nice!

The chromatin should be there:
`em-segmented-chromatin.xml`
`tables/em-segmented-chromatin.csv`

**Comment by constantinpape** [comment]
Sorry, forgot the `labels` postfix:
`em-segmented-chromatin-labels`

**Comment by tischi** [comment]
Are you doing something to the files? I all of a sudden got this, trying to read the full res raw em:

```
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5LowLevelIOException: Low-level I/O:Read failed ["H5FDsec2.c line 707 in H5FD_sec2_read(): file read failed: time = Thu Jul 11 11:43:21 2019"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Fis_hdf5(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5F.H5Fis_hdf5(H5F.java:127)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.isHDF5File(HDF5FactoryProvider.java:60)
	at ch.systemsx.cisd.hdf5.HDF5Factory.isHDF5File(HDF5Factory.java:113)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.openFile(HDF5BaseReader.java:204)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:147)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:126)
	at ch.systemsx.cisd.hdf5.HDF5ReaderConfigurator.reader(HDF5ReaderConfigurator.java:86)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.openForReading(HDF5FactoryProvider.java:54)
	at ch.systemsx.cisd.hdf5.HDF5Factory.openForReading(HDF5Factory.java:55)
```

**Comment by constantinpape** [comment]
No, I am not doing anything, but my FIJI + Platy browser just died, maybe it's related to the same issue.

**Comment by constantinpape** [comment]
I started again, and it's working for me again.

**Comment by constantinpape** [comment]
This is done.
